# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4f11e87ee4f49682305eacbcd33dfa0b469373589187da14a065559a8602a788c8f8d6e69d58592729972278166898a34f408194533977e46d6cc60caac6c4d

test:
  secret_key_base: be7287e04ab26eeec25f8d8490a01b8d6ac87f57b4168ca3a7d1259138d328a6babbdb4915c9844439b03096f68b9ca7af61e3294011d4e8e9b2120499a8c0f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
